services: 
  ipfs:
    image: ipfs/kubo:latest
    container_name: ipfs_node
    ports:
      - "4001:4001/tcp"
      - "4001:4001/udp"

      - "127.0.0.1:5001:5001"
      - "8081:8080"

    volumes: 
      - ./ipfs/ipfs_data:/data/ipfs
      - ./ipfs/ipfs_export:/export

    restart: unless-stopped

  go-backend: 
    build: ./ipfs-gestion-archivos
    container_name: go_motor_ipfs
    ports:
      - "8080:8080"
    environment:
      - IPFS_URL=http://ipfs:5001
    depends_on:
      - ipfs
    restart: unless-stopped

volumes:
  ipfs_data:
  ipfs_export: