services: 
  front-prueba:
    build: ./oguripfs-frontend
    container_name: frontend-prueba
    ports: 
      - "81:80"
    restart: unless-stopped

  oguripfs-backend:
    build: ./oguripfs-backend
    container_name: oguripfs-backend
    ports: 
      - "3000:3000"
    env_file:
      - .env
    environment:
    - DATABASE_URL=${DATABASE_URL}
    restart: unless-stopped
