name: Deploy API a Oracle ARM

on:
  push: 
    branches:
      - master
    paths:
      - 'oguripfs-backend/**'
      - 'oguripfs-frontend/**' # SOLO se ejecuta si tocas la API en TS

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Enviar archivos al servidor de Oracle
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "oguripfs-backend/,docker-compose.yml,oguripfs-frontend/" # Mandamos solo lo necesario
          target: "/home/deploy/motor-ipfs"
          rm: true
          
      - name: Levantar la infraestructura con Docker
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/deploy/motor-ipfs
            rm -f .env
            echo "CRUST_SEED='${{ secrets.CRUST_SEED }}'" >> .env
            echo "CRUST_RPC=${{ secrets.CRUST_RPC }}" >> .env
            echo "IPFS_HOST=${{ secrets.IPFS_HOST }}" >> .env
            echo "IPFS_PORT=${{ secrets.IPFS_PORT }}" >> .env
            echo "IPFS_PROTOCOL=${{ secrets.IPFS_PROTOCOL }}" >> .env
            echo "IPFS_TIMEOUT=${{ secrets.IPFS_TIMEOUT }}" >> .env
            echo "PORT=${{ secrets.PORT }}" >> .env
            echo "CORS_ORIGIN=${{ secrets.CORS_ORIGIN }}" >> .env
            echo "R2_ACCESS_KEY_ID=${{ secrets.R2_ACCESS_KEY_ID }}" >> .env
            echo "R2_SECRET_ACCESS_KEY=${{ secrets.R2_SECRET_ACCESS_KEY }}" >> .env
            echo "R2_ACCOUNT_ID=${{ secrets.R2_ACCOUNT_ID }}" >> .env
            echo "R2_BUCKET_NAME=${{ secrets.R2_BUCKET_NAME }}" >> .env
            echo "R2_BUCKET_NAME=${{ secrets.GERMANY_HOST }}" >> .env
            docker compose up -d --build oguripfs-backend # Solo reinicia este servicio
            docker image prune -f